### ISSUE TITLE
feature req: search by currency

### ISSUE THREAD

**Issue by gwpl** [mobnetic/BitcoinChecker#155]
I have trouble in finding in list of exchanges the right one having currency of my interest. It woukd be great fo type into search box for e.g. "chf" and got list if exchanges supporting such.

**Comment by MaciejCiemiega** [comment]
Hello,

Bitcoin Checker is designed that way so user have direct communication with exchange server, without any central server (of Bitcoin Checker) that transmits traffic from users to exchanges. So the communication is directly user<->exchange server. It is not possible to do such search because device doesn't have list of all currencies from exchanges until you download them manually from particular exchange server. I cannot do online search on 70 different external servers at once... this will take to much time...

Please see this issue. It's old but still relevant to this problem: https://github.com/mobnetic/BitcoinChecker/issues/79

Greetings,
MC

**Comment by gwpl** [comment]
Thanks for response!
