### ISSUE TITLE
Add exmo.com

### ISSUE THREAD

**Issue by stepus53** [mobnetic/BitcoinChecker#156]

**Comment by MaciejCiemiega** [comment]
Hmm I'm afraid that I cannot add support for it because their API simply doesn't work:\
Public urls like:
https://api.exmo.com/api_v2/market_data?pair=BTC_USD
or 
https://api.exmo.com/api_v2/pairs
just returns an empty page.

Please comment here in future when you will see that their API will work, then I will try to add support for it:)
Greetings!

**Comment by stepus53** [comment]
Lol, reply from support:
![2015-03-19 15_50_04-inbox stepus53 gmail com](https://cloud.githubusercontent.com/assets/10379521/6730662/ce57427a-ce4f-11e4-8798-2d6093dd08f5.png)

**Comment by MaciejCiemiega** [comment]
I'm closing this issue for now, please let me know if they will fix their API in future then I will reopen it.
