### ISSUE TITLE
Great app

### ISSUE THREAD

**Issue by jamezz42** [mobnetic/BitcoinChecker#193]
connection to cryptsy is flaky though. I get a connection error that persists until I reboot phone....so not likely a server side error. Other apps connected to cryptsy are functional when this one still can't connect. Please fix =-O

**Comment by jamezz42** [comment]
Update.....get error when connected to cellular network

**Comment by MaciejCiemiega** [comment]
Hello,
Cryptsy uses two servers: pubapi1.cryptsy.com and pubapi2.cryptsy.com.
Connecting to pubapi.cryptsy.com should redirect you to one of these servers. Currently first one is not working and if you are redirected to it, app won't be able to connect for some users (it's Crypsty servers that decide to which server you are connecting to, not the app):
http://pubapi1.cryptsy.com/api.php?method=orderdatav2 <- "502 Bad Gateway"
http://pubapi2.cryptsy.com/api.php?method=orderdatav2 <- works

They have their issue to solve and I cannot do anything with it. I cannot hardcode it to always use pubapi2.cryptsy.com because the situation can be different - second one can be broken and only the first one could work.

Hope you understand that.
Greetings.

**Comment by jamezz42** [comment]
thanks for responding, i see the problem now. When i change my connection I
have a  chance of being directed to the bad server. just food for thought,
 it might be possible to try to reconnect when an error is returned, loop
it to keep trying to connect until no error is returned....ensuring a good
connection

On Sat, Nov 28, 2015 at 2:24 PM, Maciej Ciemięga <notifications@github.com>
wrote:

> Hello,
> Cryptsy uses two servers: pubapi1.cryptsy.com and pubapi2.cryptsy.com.
> Connecting to pubapi.cryptsy.com should redirect you to one of these
> servers. Currently first one is not working and if you are redirected to
> it, app won't be able to connect for some users (it's Crypsty servers that
> decide to which server you are connecting to, not the app):
> http://pubapi1.cryptsy.com/api.php?method=orderdatav2 <- "502 Bad Gateway"
> http://pubapi2.cryptsy.com/api.php?method=orderdatav2 <- works
>
> They have their issue to solve and I cannot do anything with it. I cannot
> hardcode it to always use pubapi2.cryptsy.com because the situation can
> be different - second one can be broken and only the first one could work.
>
> Hope you understand that.
> Greetings.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mobnetic/BitcoinChecker/issues/193#issuecomment-160333701>
> .
>



-- 
Dan

417-860-6573
j.daniel.wakefield@gmail.com

**Comment by MaciejCiemiega** [comment]
I wouldn't want to do such workarounds. In this case this is their issue and they should just fix it.
