### ISSUE TITLE
Adding other exchanges

### ISSUE THREAD

**Issue by dhruv20051** [mobnetic/BitcoinChecker#262]
Hi, 

Please add UNOCOIN,  ZEBPAY and Bitxoxo.

**Comment by MaciejCiemiega** [comment]
Anyone feel free to create PR with those.

**Comment by akmamansoor** [comment]
I had already contacted Unocoin.com earlier this year and this is what they told me - 
"We are not an exchange and hence we do not have any bid, ask for highest, lowest or last traded prices. We are actually a trading platform for bitcoin."

However, they do provide a ticker API that tells you the buy price, sell price and average price of 1 BTC in INR (found at https://www.unocoin.com/tickerapi)

@MaciejCiemiega Is the above ticker format enough to consider Unocoin as an Exchange, with the average price replacing the last traded price in the code?

@dhruv20051 There seems to be no public API for Zebpay and Bitxoxo and they too appear to be trading platforms rather than actual exchanges. So, I have contacted their support team for those details. Will update here once I get their replies.

**Comment by akmamansoor** [comment]
I've got a reply from Zebpay quoted here: "We do not have any API at this time, nor do we have it on our roadmap. Also, we will not be able to provide you with the below details as of now.
However, we will update all our users once we have developer access available to our platform".

So no way to add Zebpay or Unocoin for now.

And there is still no reply from Bitxoxo :(

**Comment by cwbdev** [comment]
Hi,

Please add the exchange "Gatecoin.com"

Thank you guys. 
Merry Christmas!!!

**Comment by akmamansoor** [comment]
Can't add Unocoin, Zebpay or BitXOXO due to lack of proper API.
Gatecoin.com added via PR #278.

So I guess it is safe to close this issue now :)

**Comment by greekogod** [comment]
Please add liqui exchange to bitcoin checker 
it is a small exchange right now but has some great coins
thanks
link- liqui.io

**Comment by wlatermi** [comment]
Hi

Thanks for this great app Bitcoin checker i think it's one of  d best for me

But please u need to add one more exchange which is Bitx.com
To help number if people from d list of countries below cause bitx.com is one of d best exchange in this countries and it will be really great for people in this country listed to make use of this app

Global
Indonesia

Malaysia

Nigeria

Singapore

South Africa

**Comment by MaciejCiemiega** [comment]
I'm closing this one. Please create separate issues for individual exchanges. Then it is easier to track then and easier to create PR for them by anyone.
