### ISSUE TITLE
Add support for mBTC and other sub-coin units.

### ISSUE THREAD

**Issue by kiernann** [mobnetic/BitcoinChecker#615]

**Comment by MaciejCiemiega** [comment]
Sub units are already supported for BTC and LTC. What other coins do you want to support here?

**Comment by k5cents** [comment]
Oh I see the setting now. I guess I missed it because it's permanently
disabled for both Coinbase and Gemini exchanges? What am I missing to
enable this?

**Comment by MaciejCiemiega** [comment]
It is not permanently disabled,but it's active when the counter currency is BTC or LTC.

**Comment by k5cents** [comment]
Ok, after checking like a dozen exchanges I was finally able to find one
that offers BTC as a counter currency instead of a base currency... But
that exchange didn't offer USD as a base currency?

What I would like shown is the USD per mBTC value, but I can't seem to find
an exchange that offers such information. Shouldn't the app be able to take
the regular BTC-USD information offered by the Coinbase exchange and just
divide the price by 1000 to show mBTC?

I know this is something I can do in my head easily enough, I just through
it might make a good feature.

Anyway, I actually do love the app as is. Thanks for the reply.
